/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import { getProjectHash } from "@google/gemini-cli-core/dist/src/utils/paths.js";
import {
  analyzeInParallel,
  calculateSessionTelemetry
} from "./analysis-utils.js";
import type { BaseProcessResult, SessionTelemetry } from "./analysis-utils.js";
import type { ConversationRecord } from "@google/gemini-cli-core/dist/src/services/chatRecordingService.js";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { parseArgs } from "node:util";

/**
 * WARNING: The telemetry metrics calculated by this tool are currently estimates
 * and may be inaccurate. Due to the lack of granular start and end timestamps for
 * critical lifecycle events in the underlying chat log files generated by the CLI,
 * this tool relies on hardcoded heuristics and timestamp gap calculations.
 *
 * Specific limitations include:
 * - Textless Tool Calls: API latency for tool calls without preceding text is guessed
 *   (e.g., hardcoded to 1000ms), and the rest of the time is attributed to local execution.
 * - Tool Confirmation Prompts: Time spent waiting for user confirmation is indistinguishable
 *   from actual tool execution time, relying on an arbitrary threshold (e.g., 2000ms) for
 *   "fast" tools.
 * - User Idle Time: Walkaway time is determined by a hard 10-minute threshold.
 *
 * These limitations can result in a distorted view of system bottlenecks (e.g., misreporting
 * slow API responses as local tool execution time).
 */
interface SankeyTotals {
  serverSuccess: number;
  serverError: number;
  serverCancel: number;
  tools: number;
  userActive: number;
  userIdle: number;
  internal: number;
  totalSession: number;
  modelBreakdown: Record<
    string,
    { successMs: number; errorMs: number; cancelMs: number }
  >;
}

function usage() {
  const scriptName = path.basename(process.argv[1]);
  console.log(`Usage: ${scriptName} [OPTIONS] DIRECTORY OUTPUT_FILE

Generates a Sankey diagram (Mermaid format) showing where session time was spent.
Aggregates telemetry across all sessions in the target project.

Arguments:
  DIRECTORY         The directory to look up history for.
  OUTPUT_FILE       The path to write the Mermaid/Sankey output to (.md recommended).

Options:
  --limit NUMBER        Limit analysis to the N most recent conversations (default: all).
  --dump-analysis FILE  Output intermediate aggregated data to FILE (JSON format).
  -h, --help            Display this help message and exit
`);
}

async function main() {
  const { values, positionals } = parseArgs({
    options: {
      help: { type: "boolean", short: "h" },
      limit: { type: "string" },
      "dump-analysis": { type: "string" }
    },
    allowPositionals: true
  });

  if (values.help || positionals.length < 2) {
    usage();
    process.exit(values.help ? 0 : 1);
  }

  const targetDirArg = positionals[0];
  const outputFileArg = positionals[1];
  const resolvedTargetDir = path.resolve(targetDirArg);

  if (
    !fs.existsSync(resolvedTargetDir) ||
    !fs.statSync(resolvedTargetDir).isDirectory()
  ) {
    console.error(`Error: Directory '${resolvedTargetDir}' does not exist.`);
    process.exit(1);
  }

  // Find project hash
  const projectsJsonPath = path.join(os.homedir(), ".gemini/projects.json");
  let hash = getProjectHash(resolvedTargetDir);
  if (fs.existsSync(projectsJsonPath)) {
    try {
      const projectsData = JSON.parse(
        fs.readFileSync(projectsJsonPath, "utf8")
      );
      if (projectsData.projects && projectsData.projects[resolvedTargetDir]) {
        hash = projectsData.projects[resolvedTargetDir];
      }
    } catch {
      // Ignore parse errors
    }
  }

  const chatsDir = path.join(os.homedir(), ".gemini/tmp", hash, "chats");
  if (!fs.existsSync(chatsDir)) {
    console.error(
      `Error: No 'chats' directory found for this project at ${chatsDir}`
    );
    process.exit(1);
  }

  let chatFiles = fs
    .readdirSync(chatsDir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => ({
      path: path.join(chatsDir, f),
      time: fs.statSync(path.join(chatsDir, f)).mtime.getTime()
    }))
    .sort((a, b) => b.time - a.time);

  if (values.limit) {
    const limit = parseInt(values.limit, 10);
    if (!isNaN(limit)) chatFiles = chatFiles.slice(0, limit);
  }

  console.error(`Aggregating telemetry from ${chatFiles.length} sessions...`);

  const totals: SankeyTotals = {
    serverSuccess: 0,
    serverError: 0,
    serverCancel: 0,
    tools: 0,
    userActive: 0,
    userIdle: 0,
    internal: 0,
    totalSession: 0,
    modelBreakdown: {}
  };

  const processLog = async (
    filePath: string
  ): Promise<BaseProcessResult<SessionTelemetry> | null> => {
    try {
      const content = fs.readFileSync(filePath, "utf8");
      const session = JSON.parse(content) as ConversationRecord;
      if (!session.messages) return null;
      const tel = calculateSessionTelemetry(session);
      return {
        insight: tel,
        rawSize: Buffer.byteLength(content),
        filteredSize: 0 // Not needed for this tool
      };
    } catch {
      return null;
    }
  };

  const { results } = await analyzeInParallel(
    chatFiles.map((f) => f.path),
    processLog
  );

  for (const tel of results) {
    totals.serverSuccess += tel.totalWaitServerSuccessTimeMs;
    totals.serverError += tel.totalWaitServerErrorTimeMs;
    totals.serverCancel += tel.totalWaitServerCancelTimeMs;
    totals.tools += tel.totalWaitToolsTimeMs;
    totals.userActive += tel.totalWaitUserTimeMs;
    totals.userIdle += tel.totalWaitIdleTimeMs;
    totals.internal += tel.totalInternalTimeMs;
    totals.totalSession += tel.totalSessionTimeMs;

    for (const model of Object.keys(tel.modelBreakdown)) {
      if (!totals.modelBreakdown[model]) {
        totals.modelBreakdown[model] = {
          successMs: 0,
          errorMs: 0,
          cancelMs: 0
        };
      }
      totals.modelBreakdown[model].successMs +=
        tel.modelBreakdown[model].successMs;
      totals.modelBreakdown[model].errorMs += tel.modelBreakdown[model].errorMs;
      totals.modelBreakdown[model].cancelMs +=
        tel.modelBreakdown[model].cancelMs;
    }
  }

  if (values["dump-analysis"]) {
    fs.writeFileSync(
      values["dump-analysis"],
      JSON.stringify({ totals, sessionsCount: results.length }, null, 2)
    );
  }

  const mermaid = generateMermaidSankey(totals);
  const sankeyMatic = generateSankeyMatic(totals);

  const report =
    "# Active Session Time Distribution: " +
    path.basename(resolvedTargetDir) +
    "\n\n" +
    "Generated on: " +
    new Date().toISOString() +
    "\n" +
    "Sessions Aggregated: " +
    results.length +
    "\n" +
    "Total Idle Time (Excluded): " +
    formatDur(toMin(totals.userIdle)) +
    "\n\n" +
    "## Mermaid.js Diagram\n" +
    "```mermaid\n" +
    mermaid +
    "\n" +
    "```\n\n" +
    "## SankeyMatic Text Format\n" +
    "```text\n" +
    sankeyMatic +
    "\n" +
    "```\n";

  fs.writeFileSync(outputFileArg, report);
  console.error("\nSankey report written to: " + outputFileArg);
}

function toMin(ms: number) {
  return Math.max(0, Math.round(ms / 60000));
}

function formatDur(mins: number): string {
  if (mins === 0) return "0m";
  const d = Math.floor(mins / 1440);
  const h = Math.floor((mins % 1440) / 60);
  const m = mins % 60;

  const parts = [];
  if (d > 0) parts.push(d + "d");
  if (h > 0) parts.push(h + "h");
  if (m > 0 || parts.length === 0) parts.push(m + "m");
  return parts.join(" ");
}

function generateMermaidSankey(t: SankeyTotals): string {
  const sSuccess = toMin(t.serverSuccess);
  const sError = toMin(t.serverError);
  const sCancel = toMin(t.serverCancel);
  const uActive = toMin(t.userActive);
  const lTools = toMin(t.tools);
  const lInternal = toMin(t.internal);

  const modelNetwork = sSuccess + sError + sCancel;
  const user = uActive; // Idle excluded
  const local = lTools + lInternal;

  const nTotal = "Active Session Time";
  const nModel = "Model & Network";
  const nUser = "Human (Active)";
  const nLocal = "Local Environment";

  let mermaid =
    "sankey-beta\n" +
    nTotal +
    "," +
    nModel +
    "," +
    modelNetwork +
    "\n" +
    nTotal +
    "," +
    nUser +
    "," +
    user +
    "\n" +
    nTotal +
    "," +
    nLocal +
    "," +
    local +
    "\n\n";

  for (const model of Object.keys(t.modelBreakdown)) {
    const ms = toMin(t.modelBreakdown[model].successMs);
    const me = toMin(t.modelBreakdown[model].errorMs);
    const mc = toMin(t.modelBreakdown[model].cancelMs);
    const mTotal = ms + me + mc;

    if (mTotal === 0) continue;

    mermaid += nModel + "," + model + "," + mTotal + "\n";
    mermaid += model + ",Successful Responses," + ms + "\n";
    mermaid += model + ",API Errors," + me + "\n";
    mermaid += model + ",Cancelled Requests," + mc + "\n\n";
  }

  mermaid += nUser + ",Active Thinking/Prompts," + uActive + "\n\n";
  mermaid += nLocal + ",Tool Execution," + lTools + "\n";
  mermaid += nLocal + ",CLI Internal," + lInternal;

  return mermaid;
}

function generateSankeyMatic(t: SankeyTotals): string {
  const sSuccess = toMin(t.serverSuccess);
  const sError = toMin(t.serverError);
  const sCancel = toMin(t.serverCancel);
  const uActive = toMin(t.userActive);
  const lTools = toMin(t.tools);
  const lInternal = toMin(t.internal);

  const modelNetwork = sSuccess + sError + sCancel;
  const user = uActive; // Idle excluded
  const local = lTools + lInternal;

  const nTotal = "Active Session Time";
  const nModel = "Model & Network";
  const nUser = "Human (Active)";
  const nLocal = "Local Environment";

  let matic =
    nTotal +
    " [" +
    modelNetwork +
    "] " +
    nModel +
    "\n" +
    nTotal +
    " [" +
    user +
    "] " +
    nUser +
    "\n" +
    nTotal +
    " [" +
    local +
    "] " +
    nLocal +
    "\n\n";

  for (const model of Object.keys(t.modelBreakdown)) {
    const ms = toMin(t.modelBreakdown[model].successMs);
    const me = toMin(t.modelBreakdown[model].errorMs);
    const mc = toMin(t.modelBreakdown[model].cancelMs);
    const mTotal = ms + me + mc;

    if (mTotal === 0) continue;

    matic += nModel + " [" + mTotal + "] " + model + "\n";
    matic += model + " [" + ms + "] Successful Responses\n";
    matic += model + " [" + me + "] API Errors\n";
    matic += model + " [" + mc + "] Cancelled Requests\n\n";
  }

  matic += nUser + " [" + uActive + "] Active Thinking/Prompts\n\n";
  matic += nLocal + " [" + lTools + "] Tool Execution\n";
  matic += nLocal + " [" + lInternal + "] CLI Internal";

  return matic;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
